### ISSUE TITLE
Showing set of posts again

### ISSUE THREAD

**Issue by bonanza123** [Alex217/GagBook#2]
Occasionally, I see a collection of posts in a loop, like:
A
B
C
D
E
C
D
E
C
D
E
F
G
H
...

If it's not reproducible for you, please advise me how to obtain debug logs.

**Comment by Alex217** [comment]
Yes this issue arises sporadically and this could be a bug of the API itself.

I just published v1.4.2. I changed the API calls to fetch 9 posts instead of 10, since this caused some issues (e.g. that GagBook was suddenly not able to fetch the posts properly and gave the 'Reached end of the list'-message). The API seems to be buggy and it seems to be only working properly with the default settings. :D

Please try it out and report if this issue has been fixed with that version.

**Comment by bonanza123** [comment]
way much better now, thanks!

**Comment by Alex217** [comment]
Great, thanks for the confirmation. :)

---

For the sake of completeness: Commit 20152c3 fixed this issue.
